# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

#FIXME see https://github.com/inveniosoftware/invenio-access/issues/129
dist: trusty

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true
  allow_failures:
    - env: REQUIREMENTS=devel EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
    - env: REQUIREMENTS=devel EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
    - env: REQUIREMENTS=devel EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"

cache:
  - pip

services:
  - mysql
  - postgresql
  - redis-server

env:
  - REQUIREMENTS=lowest EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=lowest EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
  - REQUIREMENTS=lowest EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  - REQUIREMENTS=release EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=release EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
  - REQUIREMENTS=release EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio" DEPLOY=true
  - REQUIREMENTS=devel EXTRAS=all,sqlite SQLALCHEMY_DATABASE_URI="sqlite:///test.db"
  - REQUIREMENTS=devel EXTRAS=all,mysql SQLALCHEMY_DATABASE_URI="mysql+pymysql://root@localhost:3306/invenio"
  - REQUIREMENTS=devel EXTRAS=all,postgresql SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"

python:
  - "2.7"
  - "3.5"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"
  - "mysql -e 'CREATE DATABASE IF NOT EXISTS invenio; GRANT ALL ON invenio.* TO 'root';' -uroot"
  - "psql -c 'CREATE DATABASE invenio;' -U postgres"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[${EXTRAS}]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: jirikuncar
  password:
    secure: eGwqt2lkoiY/h82+G3XUpcEwIqUQS7V6MS4Itl4bz0P1+1ctZxMRxkVrQpAa6XMg/6Sgy9c2osI2VU6TtSpoB515PWvzbil/OI0tyL2VaPpMi3I55wZuT08kvwVIKAl695UYNONJ4ocPdwOKhl+ht7jtsbgxYoQBlbdh0zps26S2jJnQLa6WauVD0CSVdXYEiwLaFZ5clndqeZaEAOmIJIfkYkk0dlD6N24r5ULgQkoT2d3X2BgzEXX8m/k6wT2bWifMzls/XOtv4pTXHdFlRGF5xgEqalg+sHQ1+DuEtS4OK3azRiKgC7W8cBEyf6O79/jD3ifVKYxaRon9EioJoMBszuPpgZnRTJlRDv/JTzBq5yBU/sTarQku3XIhHxJOJGEvcfgIfpXUN2iwdj2itaYlBs9ItX/28ZhFo3GSPeJxA0Qrvp95/Uls9RLUIkm5gnIpBb3Q0A9xWT3/qRWlSLiSkWeVdslCdWQryBxrhMWSACoyO1gvYgpC6xI+jkNYgHktJ+y6YlF5ANaXvTq1lSdtZ5A2egBeHf8qTPQ7tX37dLaYANQVBslIkxqNzaXkmwtgUh4s4Sb97CwGOY+ftlhDkCx0JlhS2vbEvv6itaWpYB2AEhC79vq7zi+3uMGXwBIRQQeCd3lPYj9kwkbBwYdzg3VTH1fmZUsrpIDST4U=
  distributions: "compile_catalog sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    condition: $DEPLOY = true
